name: "Build and Deploy"
on:
  push:
    branches:
      - master
jobs:
  buid:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        
      - name: Restore packages
        run: dotnet restore
      
      - name: Build
        run: dotnet publish src/Host/Host.csproj --configuration release --no-self-contained --framework net8.0 --output ./publish --runtime linux-x64 /nodereuse:false