name: "Build and Deploy"
on:
  push:
    branches:
      - master
jobs:
  buid:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        
      - name: Restore packages
        run: dotnet restore
      
      - name: Build
        run: docker build -f Dockerfile -t ${IMAGE_NAME}