name: "Deploy"
on:
  workflow_dispatch:
    

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Delete old containers
        run: docker rm -f torrentwatcher || true
      - name: Deploy
        run: docker run --name=torrentwatcher --publish 8080:8080 --detach --restart=always --network=database --env "TelegramSettings__Token"=${{secrets.TOKEN}} --env "TelegramSettings__ChatId"=${{secrets.CHAT_ID}} --env "ConnectionStrings__postgresConnection"=${{secrets.CONNECTION_STRING}} torrentwatcher:latest